export const TEST_PORT_VARIABLE = 3000;
export const TEST_DB_ADDRESS_VARIABLE = 'mongodb://127.0.0.1/server_test_db';
export const TEST_ENCRYPTION_SALT_VARIABLE = 10;
export const TEST_TOKEN_SECRET_VARIABLE = 'test_secret';
export const TEST_TOKEN_VALIDITY_VARIABLE = '1d';

process.env.PORT = TEST_PORT_VARIABLE.toString();
process.env.DB_ADDRESS = TEST_DB_ADDRESS_VARIABLE;
process.env.ENCRYPTION_SALT = TEST_ENCRYPTION_SALT_VARIABLE.toString();
process.env.TOKEN_SECRET = TEST_TOKEN_SECRET_VARIABLE;
process.env.TOKEN_VALIDITY = TEST_TOKEN_VALIDITY_VARIABLE;
