name: coverage
on: [pull_request]

jobs:
  compare-cov:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: vgrafe/couette@v0.123
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
