name: On pull request

on:
  pull_request:
    branches: [ '**' ]

jobs:

  test:
    uses: Tale152/express-server-template/.github/workflows/reusable-test-matrix.yml@master

  cpd:
    if: github.actor != 'dependabot[bot]' || github.actor != 'dependabot-preview[bot]'
    needs: test
    uses: Tale152/express-server-template/.github/workflows/reusable-cpd.yml@master

  autoapprove:
    name: Auto-Approve a PR by dependabot
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: cognitedata/auto-approve-dependabot-action@v3.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
