name: On pull request

on:
  pull_request:
    branches: [ '**' ]

jobs:

  test:
    uses: Tale152/express-server-template/.github/workflows/reusable-test-matrix.yml@master

  cpd:
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: test
    uses: Tale152/express-server-template/.github/workflows/reusable-cpd.yml@master

  approve-dependabot-request:
    if: ${{ github.actor == 'dependabot[bot]' }}
    name: Approve a PR by dependabot
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
