name: CI

on:
  push:
    branches: [ '**' ]

jobs:

  coverage-badge:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: Tale152/express-server-template/.github/workflows/reusable-coverage-badge.yml@master
