name: coverage
on: [pull_request]

jobs:
  compare-coverage:
    runs-on: ubuntu-latest
    name: Compare coverage
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: vgrafe/couette@v0.123
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  compare-cpd:
    runs-on: ubuntu-latest
    name: Compare cpd
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Dry Code Action
        uses: Pposong-Hantaihe/dry-code@v1.0.2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

  compare-eslint:
    runs-on: ubuntu-latest
    name: Compare eslint
    steps:
    - uses: actions/checkout@v2
    - uses: bradennapier/eslint-plus-action@v3.4.2
