name: Update coverage badge

on:
  workflow_call:

jobs:
  update-badge:
    name: Update coverage badge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Start MongoDB v4.2
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: 4.2
      - name: Install dependencies
        run: npm ci
      - name: Generate coverage report
        run: npm test
      - name: Update badge
        run: npm run coverage:badge
      - id: Generate cpd report
        run: npm run cpd
      - name: Get coverage percentage
        id: coverage_percentage
        uses: notiz-dev/github-action-json-property@release
        with:
            path: 'report/jscpd-report.json'
            prop_path: 'statistics.total.percentage'
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: CPD
          LABEL: 'CPD'
          STATUS: ${{steps.coverage_percentage.outputs.prop}}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
