name: Update badges

on:
  workflow_call:
  workflow_dispatch:

jobs:
  update-badge:
    name: Update coverage badge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Start MongoDB v4.2
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: 4.2
      - name: Install dependencies
        run: npm ci
      - name: Generate coverage report
        run: npm test
      - name: Update coverage badge
        run: npm run coverage:badge
      - name: Generate cpd report
        run: npm run cpd
      - name: Update cpd badge
        uses: canastro/copy-file-action@master
        with:
          source: "report/jscpd-badge.svg"
          target: ".github/badges/jscpd-badge.svg"
      - name: Push changes
        uses: actions-go/push@master
        with:
          commit-message: '[Auto] Updated coverage badge and/or cpd badge'
          author-name: 'github-actions[bot]'
          author-email: 'github-actions[bot]@users.noreply.github.com'
