name: Update coverage badge

on:
  workflow_call:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Start MongoDB v4.2
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: 4.2
      - name: Install dependencies
        run: npm ci
      - name: Generate report
        run: npm test
      - name: Update badge
        run: npm run coverage:badge
      - name: Push changes
        - uses: mikeal/publish-to-github-action@master
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
